sudo: false
dist: trusty
services:
  - postgresql: "9.5"
language: python
python:
  - "3.5"
  - "3.6"
env:
  global:
    - DEBUG=True
    - ALLOWED_HOSTS=*
    - POSTGRES_DB=aprigi
    - POSTGRES_USER=postgres
    - POSTGRES_HOST=127.0.0.1
    - POSTGRES_PORT=5432
    - EMAIL_PORT=587
    - EMAIL_USE_TLS=True
    - secure: "BsOShGSSAloN+d6e8Sb2WI2Mwu1qO3tnO+oZ8P/TaKaaOAMOu4/WJKNwFQH/2c4RFqAJxS0TNkXo5f2sPCvgYW6wxS8mvAEKWwDO/0rkRvuX57GFChO+IzWKnzJ8ArpgkXMpq03StKcePvwh5vIylB3aDtJ+xE9QiBaDXRejibFw2WW+PxpX+colFbk3l+E7x+FHdPw8aEBnduYL4hgbC/FlzF0MvdrS/0nd7zIrT05Nrc08eatUPO6MKiltMavL3uWeqGTcsVWUkXofv+fxHAZjZg7NoJhqjTaPgyucwvVaKpdk08GNlk5wA0qub7RrCcWzr3EdUNO9Op5C09CYhcKMvJ67pheun8SGYaN5iPRLsk6A8bwO5HFPT9TZEqBht8pPAngktTto/yWoAq1e2I0ufr5Yn9usMVaGS0tD9tNH1mrAAQsj64vsQA5OIcvNW7B/s7mNgxnhN34JjHyjKdkx1p+m+xc9T2Opgg3b9/XXQojK8/621FU+ztmoAALYI3pNYZV0Mtoa+4ZHlX1VBEOGmql0K53ib5zz6Agk23TEBfmI3cqIjz1MK3LSRIYkQCs+v5ifKGtEap9cjjim5lM/YRzB/smX8icGocy22e4HQjWX68FV+JlU85jNpNU2Fyw+m1Cxopm9cyuA2aSiXTqOHERrDe545NJ0TylfSyk="
    - secure: "VlQjf1+8xCYE7HxdajJZj7/OlkZ+5GcxFMys7BH6vB/nGETb3NIxprZqD7m7ZDvkiQbHS09OKTqGbiql1HmA9JEOaDTijxBZRabyyDXG7ti85jrh+sS6enA9EpqAzuKmyFBpjcv3OyOR9lIyff9/VHV5Cha5fDA5Z21g0wCR7vEf8q3vlkPB1Bj6/1L9lby46rN/RiHSB4IsqCaJ8hSS0fSkyTBcoPu6D7NxuI5P7OaMHvkMZRuLHxSJSawcaTmRc7YHZwHZ7qzVGZ2Y0pMkVLpvaEt9CFX03FwhNPcyNSze04vsIb/mr8kSmFtCmIF+TNqAJ0TGfm4shNiNP1kpdHb9gZsGTm/XUXbXD142POoS7j11ZcaF8VESk43dumLfrbs8o3T+hmx74ZhAVwegNdjLOKckIQnHr0Dd7cXGIJ8smv0t8IKpzYUg9VoZ19eza4iCDqW47iljCgprngXZfi8+YrbUxyHYUNv7cW6c9L3kUgC3VXuxyS34T++VwRS2C3itQdoHakZnz989Yya9itVaxfrQCWSedB2i5vw9+29AuYpiOCTljmhXv20B9TyRWP/15EGtuBy6JLFg/puHnHYqqvFZs9ZS7sEttse1h2mNOCzGnGEeY2VCbJ/qpFTPwZQS2rqXvgzrEOex8PmObuv14lz/VKpd4lIJyaYlaEY="
    - secure: "GJDH4hrXJmfysHSjQkYFQGHKuze9R7E8gSNAnZMfzDlY/UosiCpkWQfX/oZEANv2hNbmoTsXlH7iBUxfC1AoYzSs+r/BVUz9XkLug/BZz/+b/EISAajTBZVEFBpPwX2BMy6q20YqPcQ6ceBiQrcsQzprv9tXP9T0Ae403hedK6veQ3lRDTQPlKFXUsIibPfNEARG+dtbHEsUo/MzKCzQ3jB0vtDoD8i30eIR7+S1cDnlSVEcz/UG6FMDk/ljWwk90bofP7cuSKzl2zwSwSsO3giOPmeF7q1dQCRR/JlnQtaYl5qyPiqMd35B0PybBPKieitjom+cGLJ3dRt8APlp8E+/Rh0xSSAjvmjyKISEggkV7ysU5CparLInBgvJI4nPQMfxCEHL3D3QIjsM7uQ0iQYmw6FSri8HeSW0XbbLOZPC4KH0shW7Ru5+8OfMcTw+uIoGvYD+jzp1iDDhR3cWGfd+ietOLr+jHirNr526Yr1bC29Vvi2G7svab6zZ5eIqX28haGr8pYaPFEEjFDT3kGf7xPO+TnZsImQTh7VXglAoYNHsLY3CxDoYHLdptjPTTdlnuTKgnpcFm5Ok7ZbTTyvRnw0NmKJ/yHbNLKjzPJwVAnLjtXDuub+3mEDzgbTXAI8u/R6FeeDpBiU5w2jQnVjM8cagxFr8VrxWBlCvkC8="
    - secure: "NspxZuTKSfXu2KH2e8qsVIAXEzytxI/Yt5HrIZVK7tDNbaP88diijN1ALhL/5ekEGoYLEg0bEZMtE2oFzhKlZp0hgK2/ux5vqHuVphBaVEwcOJF/d+f0dbcab/Xn3Q0UUMsqYwXKhloPpezLu7k13ps9X8M3UC60HMLppPrNC7sHYyD3zlRzElioaBXeMgwRIKE7Ijcvyg+zGq/PucuKvzP4lhCQj2JdkyRxSNSviQCqjzkfb6N0BK5o76Nwj5xR+yEBvXLd1SZQ22/nKzLL3ciAISOCdCNGyfsGM7Yt2klMEEl8u0ALb+6bvQyOo1GKkrTkZqAVcJdw9CP5kKIepSxcBr5v8Fnh3h30oLPp5wy0pmxfEC60Pf9QT5R/IwPv76vlHcQjB0MqqnB3LDhtGEefzW9Ui0Cm5VSClBeYyjKY52MksYNbSh0ZNJFA6tAx8gUkpoToZdInsmm+FF6sa+3+5LK1OfXI7wdJ9MvOb51bKyVXDwhZKsGtv1H3B1wUtMOVTeLO219j7kcAmg0YxflsJvugVbb1BI531PG1G2TsC4JB2qKB/XaawmehUqklZYeS0TMw0m36PLUuNWUh+cmA69fZrVIMn0Y0riZVvO1CW6U+RTOLfEFL507mp4KaVjHGpFW2WhKGw5rBYOyr7R+05unIz5YEW30GTtUNj1k="
install:
  - pip install tox
before_script:
  - psql -c 'create database "aprigi";' -U postgres
script:
  - tox
notifications:
  email:
    recipients:
      - secure: "U7jeOAZ9NvCAsHJLOfdndMZ1l+7ixPLey7TSqw8fOvzB8AcpvIYy90KLFtezElrorlt8lSdbcjxmZbDS2wA61lgsTo2pqX3tHG9VoC37BAAed+fc1hOo1p66XyhGyAbVbbuh45KgXySPKHp+zDIeIygCfUnmv6++2t83o9hUR16ufozI1hbeEnrExih5ZrO9d9vjxWNxPzQ14Ll1RKhDYhQ7ziV6wpf7Ev3//i+ynmOSL0OamAmV4FiEOKBZBUUdP7agP+i2FkA/RdYi6+qtOCt53wHWnyFycBsRrjCMLM5Z1Zhc9mERAG1AXFXCmOZSc47R2Ug7FhwtwR1ayS/l/yKKA3rT74c4ELxHRfXO+T+XimWFZEZKxhofuZw1TmfGlp2Ee5C56f7GBVm+dZGhtdOwGi0rmxkbyQEXbuWC135ZYCNTvA25VJSwM8OF+UaJ5YIBX3tNcuiuukZHCdQKIKK2Nh95kxhCHlmBTuJlzj1gHdyD41RP3c+sbpb7UyovqrrPHpUptm4FRQRuO0dxARkeYi84b5lE1Zf4vCzQD62HpqLlqckEdtIx8DpvlXK1dH0Sr3qS/YfReDEdHBQiGV2Qg2aKVzGPwrYvDMwhL3/KReOCzR20je//AbZhEU7q6/0QI7YM8rLPMxBXIJh6njw8wB8wUubeVM2Bd6Id7KU="
    on_success: always
    on_failure: always
