# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='number')),
                ('account_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='account number')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('period_type', models.IntegerField(choices=[(1, 'Week'), (2, 'Month')], default=2, verbose_name='period type')),
                ('period', models.IntegerField(verbose_name='period')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('stop_date', models.DateField(verbose_name='stop date')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='is open')),
                ('notes', models.CharField(max_length=200, verbose_name='notes')),
            ],
        ),
    ]
