# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20160608_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True, verbose_name='year')),
                ('amount', models.IntegerField(null=True, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
    ]
