# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('kind', models.IntegerField(choices=[(0, 'Income'), (1, 'Expense')], default=0, verbose_name='kind')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='balance changed on')),
                ('notes', models.CharField(max_length=200, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
