# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20160624_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='balance changed on'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Income'), (1, 'Expense')], db_index=True, default=0, verbose_name='kind'),
        ),
    ]
